### ISSUE TITLE
Option to set Return-Path

### ISSUE THREAD

**Issue by dacook** [hmbashar/CB-Change-Mail-Sender#1]
The return-path email header is used to process bounces from your emails ([ref](https://www.mailgun.com/resources/learn/glossary/return-path/)). For some reason, Wordpress sets it to an unhelpful address based on the server username and hostname (eg www-data@myserver.net).

This results in email bounces and auto-replies going back to the wrong address and failing. End users then receive multiple delivery failure notifications, which is not a good look!

**Feature request:** I think this plugin could easily solve this problem by adding a new input field, or a tickbox to set the return-path the same as the 'from' address.

**Comment by dacook** [comment]
Here's some sample code found here: https://www.kinamo.be/en/support/faq/correctly-setting-return-path-for-wordpress-mail-functionality

```
<?php
/*
Plugin Name: Email Return Path Fix
Author: Abdussamad Abdurrazzaq
*/
class email_return_path {
   function __construct() {
  add_action( 'phpmailer_init', array( $this, 'fix' ) );   
   }

function fix( $phpmailer ) {
    $phpmailer->Sender = $phpmailer->From;
}
}

new email_return_path();
?>
```

**Comment by hmbashar** [comment]
Hi, Thanks for the share but the plugin already sold out to someone, so I can't continue the plugin more.
